### ISSUE TITLE
能导出考试的答案吗

### ISSUE THREAD

**Issue by q82415670** [aglorice/Raincourse#1]
希望再加个自动看视频的功能

**Comment by aglorice** [comment]
不是可以导出答案吗，json格式的，视频不会做了，没时间，如果以后有时间会继续维护。

**Comment by aglorice** [comment]
> 希望再加个自动看视频的功能

不过竟然有人用，没想到，哈哈哈

**Comment by q82415670** [comment]
> > 希望再加个自动看视频的功能
> 
> 不过竟然有人用，没想到，哈哈哈

![image](https://github.com/aglorice/Raincourse/assets/110165439/6db46d94-6d56-42e7-9e4b-7da910b37e98)

**Comment by q82415670** [comment]
> > 希望再加个自动看视频的功能
> 
> 不过竟然有人用，没想到，哈哈哈

查不到课  有人用是肯定的 总要有小白鼠嘿嘿
帮你测BUG

**Comment by aglorice** [comment]
> > > 希望再加个自动看视频的功能
> > 
> > 不过竟然有人用，没想到，哈哈哈
> 
> 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> 帮你测BUG
> 

这个只是雨课堂的

**Comment by q82415670** [comment]
> > > > 希望再加个自动看视频的功能
> > > 
> > > 
> > > 不过竟然有人用，没想到，哈哈哈
> > 
> > 
> > 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> > 帮你测BUG
> 
> 这个只是雨课堂的

能适配长江雨课堂吗 大体都是一样的 应该改一下域名就行了

**Comment by aglorice** [comment]
> > > 希望再加个自动看视频的功能
> > 
> > 不过竟然有人用，没想到，哈哈哈
> 
> 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> 帮你测BUG
> 

确实bug 有点多，没管其他的，只是为了自己的期末平时分，花了一天写的，很多题型都没做，如果有机会，再来优化了。

**Comment by q82415670** [comment]
> > > > 希望再加个自动看视频的功能
> > > 
> > > 
> > > 不过竟然有人用，没想到，哈哈哈
> > 
> > 
> > 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> > 帮你测BUG
> 
> 确实bug 有点多，没管其他的，只是为了自己的期末平时分，花了一天写的，很多题型都没做，如果有机会，再来优化了。

还好 目前能适配选择多选就可以了

**Comment by q82415670** [comment]
> > > > 希望再加个自动看视频的功能
> > > 
> > > 
> > > 不过竟然有人用，没想到，哈哈哈
> > 
> > 
> > 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> > 帮你测BUG
> 
> 确实bug 有点多，没管其他的，只是为了自己的期末平时分，花了一天写的，很多题型都没做，如果有机会，再来优化了。

麻烦能不能告诉我配置文件域名该
改哪个

**Comment by aglorice** [comment]
> > > > > 希望再加个自动看视频的功能
> > > > 
> > > > 
> > > > 不过竟然有人用，没想到，哈哈哈
> > > 
> > > 
> > > 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> > > 帮你测BUG
> > 
> > 确实bug 有点多，没管其他的，只是为了自己的期末平时分，花了一天写的，很多题型都没做，如果有机会，再来优化了。
> 
> 麻烦能不能告诉我配置文件域名该
> 改哪个

你可以试试，但是我估计可能换域名还是不行，请求的接口全在api，到时候没考虑适配处了与课堂之外的，所以没有做域名配置

**Comment by q82415670** [comment]
> > > > > > 希望再加个自动看视频的功能
> > > > > 
> > > > > 
> > > > > 不过竟然有人用，没想到，哈哈哈
> > > > 
> > > > 
> > > > 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> > > > 帮你测BUG
> > > 
> > > 
> > > 确实bug 有点多，没管其他的，只是为了自己的期末平时分，花了一天写的，很多题型都没做，如果有机会，再来优化了。
> > 
> > 
> > 麻烦能不能告诉我配置文件域名该
> > 改哪个
> 
> 你可以试试，但是我估计可能换域名还是不行，请求的接口全在api，到时候没考虑适配处了与课堂之外的，所以没有做域名配置

那我就跪求大佬适配了！！！！看你了大佬！！！！！

**Comment by aglorice** [comment]
> > > > > > > 希望再加个自动看视频的功能
> > > > > > 
> > > > > > 
> > > > > > 不过竟然有人用，没想到，哈哈哈
> > > > > 
> > > > > 
> > > > > 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> > > > > 帮你测BUG
> > > > 
> > > > 
> > > > 确实bug 有点多，没管其他的，只是为了自己的期末平时分，花了一天写的，很多题型都没做，如果有机会，再来优化了。
> > > 
> > > 
> > > 麻烦能不能告诉我配置文件域名该
> > > 改哪个
> > 
> > 你可以试试，但是我估计可能换域名还是不行，请求的接口全在api，到时候没考虑适配处了与课堂之外的，所以没有做域名配置
> 
> 那我就跪求大佬适配了！！！！看你了大佬！！！！！

看看吧，可能得明年，哈哈😄，备考，如果有人提pr那就最好，好像github上，还没有类似的

**Comment by q82415670** [comment]
> > > > > > > > 希望再加个自动看视频的功能
> > > > > > > 
> > > > > > > 
> > > > > > > 不过竟然有人用，没想到，哈哈哈
> > > > > > 
> > > > > > 
> > > > > > 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> > > > > > 帮你测BUG
> > > > > 
> > > > > 
> > > > > 确实bug 有点多，没管其他的，只是为了自己的期末平时分，花了一天写的，很多题型都没做，如果有机会，再来优化了。
> > > > 
> > > > 
> > > > 麻烦能不能告诉我配置文件域名该
> > > > 改哪个
> > > 
> > > 
> > > 你可以试试，但是我估计可能换域名还是不行，请求的接口全在api，到时候没考虑适配处了与课堂之外的，所以没有做域名配置
> > 
> > 
> > 那我就跪求大佬适配了！！！！看你了大佬！！！！！
> 
> 看看吧，可能得明年，哈哈😄，备考，如果有人提pr那就最好，好像github上，还没有类似的

这点小问题我相信难不倒大佬你的！！！！！！相信你分分钟就能搞定！！！！正是因为GIT上没有 我才看中了你的潜力！！！！相信你很快就能做出来！！！！

**Comment by aglorice** [comment]
> > > > > > > > > 希望再加个自动看视频的功能
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不过竟然有人用，没想到，哈哈哈
> > > > > > > 
> > > > > > > 
> > > > > > > 查不到课  有人用是肯定的 总要有小白鼠嘿嘿
> > > > > > > 帮你测BUG
> > > > > > 
> > > > > > 
> > > > > > 确实bug 有点多，没管其他的，只是为了自己的期末平时分，花了一天写的，很多题型都没做，如果有机会，再来优化了。
> > > > > 
> > > > > 
> > > > > 麻烦能不能告诉我配置文件域名该
> > > > > 改哪个
> > > > 
> > > > 
> > > > 你可以试试，但是我估计可能换域名还是不行，请求的接口全在api，到时候没考虑适配处了与课堂之外的，所以没有做域名配置
> > > 
> > > 
> > > 那我就跪求大佬适配了！！！！看你了大佬！！！！！
> > 
> > 看看吧，可能得明年，哈哈😄，备考，如果有人提pr那就最好，好像github上，还没有类似的
> 
> 这点小问题我相信难不倒大佬你的！！！！！！相信你分分钟就能搞定！！！！正是因为GIT上没有 我才看中了你的潜力！！！！相信你很快就能做出来！！！！

哈哈，有机会我会修的。
